apiVersion: v1
kind: Service
metadata:
  name: customerorderservices
  labels:
    app: customerorderservices
spec:
  ports:
    - port: 80
      targetPort: 9080
  selector:
    app: customerorderservices
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: customerorderservices
  name: customerorderservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customerorderservices
    spec:
      containers:
      - image: bluedemocluster.icp:8500/purplecompute/customer-order-services:liberty
        name: customerorderservices
        ports:
        - containerPort: 9080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: orderdb
        - configMapRef:
            name: ldap
